/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/empty': RouteRecordInfo<'/empty', '/empty', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
    '/oops': RouteRecordInfo<'/oops', '/oops', Record<never, never>, Record<never, never>>,
    '/organizations': RouteRecordInfo<'/organizations', '/organizations', Record<never, never>, Record<never, never>>,
    '/organizations/[organizationId]/settings': RouteRecordInfo<'/organizations/[organizationId]/settings', '/organizations/:organizationId/settings', { organizationId: ParamValue<true> }, { organizationId: ParamValue<false> }>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/projects/[projectId]/backlogs': RouteRecordInfo<'/projects/[projectId]/backlogs', '/projects/:projectId/backlogs', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/boards': RouteRecordInfo<'/projects/[projectId]/boards', '/projects/:projectId/boards', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/dashboards': RouteRecordInfo<'/projects/[projectId]/dashboards', '/projects/:projectId/dashboards', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/personas': RouteRecordInfo<'/projects/[projectId]/personas', '/projects/:projectId/personas', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/retrospectives/[[retrospectiveId]]': RouteRecordInfo<'/projects/[projectId]/retrospectives/[[retrospectiveId]]', '/projects/:projectId/retrospectives/:retrospectiveId?', { projectId: ParamValue<true>, retrospectiveId?: ParamValueZeroOrOne<true> }, { projectId: ParamValue<false>, retrospectiveId?: ParamValueZeroOrOne<false> }>,
    '/projects/[projectId]/settings': RouteRecordInfo<'/projects/[projectId]/settings', '/projects/:projectId/settings', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/sprints': RouteRecordInfo<'/projects/[projectId]/sprints', '/projects/:projectId/sprints', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/summary': RouteRecordInfo<'/projects/[projectId]/summary', '/projects/:projectId/summary', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/tags/': RouteRecordInfo<'/projects/[projectId]/tags/', '/projects/:projectId/tags', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/tags/import': RouteRecordInfo<'/projects/[projectId]/tags/import', '/projects/:projectId/tags/import', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/wiki-pages/': RouteRecordInfo<'/projects/[projectId]/wiki-pages/', '/projects/:projectId/wiki-pages', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/wiki-pages/[wikiPageId]/': RouteRecordInfo<'/projects/[projectId]/wiki-pages/[wikiPageId]/', '/projects/:projectId/wiki-pages/:wikiPageId', { projectId: ParamValue<true>, wikiPageId: ParamValue<true> }, { projectId: ParamValue<false>, wikiPageId: ParamValue<false> }>,
    '/projects/[projectId]/wiki-pages/[wikiPageId]/edit': RouteRecordInfo<'/projects/[projectId]/wiki-pages/[wikiPageId]/edit', '/projects/:projectId/wiki-pages/:wikiPageId/edit', { projectId: ParamValue<true>, wikiPageId: ParamValue<true> }, { projectId: ParamValue<false>, wikiPageId: ParamValue<false> }>,
    '/projects/[projectId]/wiki-pages/new': RouteRecordInfo<'/projects/[projectId]/wiki-pages/new', '/projects/:projectId/wiki-pages/new', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/wisdom-extractor': RouteRecordInfo<'/projects/[projectId]/wisdom-extractor', '/projects/:projectId/wisdom-extractor', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/projects/[projectId]/work-items': RouteRecordInfo<'/projects/[projectId]/work-items', '/projects/:projectId/work-items', { projectId: ParamValue<true> }, { projectId: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
